name = "view-counter-test"

compatibility_date = "2023-07-24"
main = "./src/index.ts"

send_metrics = false
workers_dev = true

[[d1_databases]]
binding = "ViewCounter" # i.e. available in your Worker on env.DB
database_id = "d525b9b6-329c-4d68-83dc-14a0da94e8e6" 
database_name = "ViewCounter2"
